# Generated by Django 4.2.19 on 2025-02-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='lang',
        ),
    ]
